import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CONTEXT_GRAPH_SCHEMA,
  type ContextGraphEdge,
  type ContextGraphNode,
  type ContextGraphSnapshot
} from '../../../contracts.js';
import { analyzeArchitectureFindings } from '../../../architecture/findings.js';
import { buildArchitectureInputBundle } from '../../../architecture/input-bundle.js';
import { loadArchitectureMapPolicy } from '../../../architecture/policy.js';
import { GENERATED_HEADER } from '../contracts.js';
import { mermaidLabel } from '../escape.js';
import { buildModuleDependencyView } from '../module-dependency.js';
import { serializeMermaidDocument } from '../serializer.js';
import * as ast from '../ast.js';
import { mermaidNodeId } from '../ids.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../../../..');

function node(id: string, overrides: Partial<ContextGraphNode> = {}): ContextGraphNode {
  return {
    id,
    kind: 'module',
    label: id,
    trust: 0.9,
    freshness: 'fresh',
    risk: 'low',
    tokenCost: 8,
    metadata: {},
    path: id.startsWith('module:') ? id.slice('module:'.length) : id,
    ...overrides
  };
}

function edge(from: string, to: string, type: ContextGraphEdge['type'], id?: string): ContextGraphEdge {
  return {
    id: id ?? `edge:${from}->${to}:${type}`,
    from,
    to,
    type,
    confidence: 'exact',
    provenance: { path: 'src/a.ts', hash: 'abcd', extractor: 'test' },
    observedAt: '2026-01-01T00:00:00.000Z'
  };
}

function snapshot(nodes: ContextGraphNode[], edges: ContextGraphEdge[]): ContextGraphSnapshot {
  return {
    schema: CONTEXT_GRAPH_SCHEMA,
    schemaRevision: '1.0.0',
    snapshotHash: 'b'.repeat(64),
    nodes: [...nodes],
    edges: [...edges],
    cycles: [],
    extractors: [],
    nodeCount: nodes.length,
    edgeCount: edges.length
  };
}

test('serializeMermaidDocument is deterministic for the same AST', () => {
  const idA = mermaidNodeId('module:src/a');
  const idB = mermaidNodeId('module:src/b');
  const doc = ast.document({
    direction: 'TD',
    title: 'Determinism check',
    statements: [
      ast.comment('atlas-view: module-dependency'),
      ast.node({ id: idA, label: 'src/a', canonicalNodeIds: ['module:src/a'] }),
      ast.node({ id: idB, label: 'src/b', canonicalNodeIds: ['module:src/b'] }),
      ast.edge({
        from: idA,
        to: idB,
        relation: 'imports',
        canonicalEdgeIds: ['e1'],
        fromCanonicalId: 'module:src/a',
        toCanonicalId: 'module:src/b'
      })
    ]
  });
  const first = serializeMermaidDocument(doc);
  const second = serializeMermaidDocument(doc);
  assert.equal(first, second);
  assert.ok(first.startsWith(GENERATED_HEADER));
  assert.match(first, /^%% GENERATED BY SKS\. DO NOT EDIT\./m);
});

test('mermaidLabel escapes malicious label characters', () => {
  const escaped = mermaidLabel('evil|"<script>`#');
  assert.equal(escaped.includes('"'), false);
  assert.equal(escaped.includes('<'), false);
  assert.equal(escaped.includes('>'), false);
  assert.equal(escaped.includes('|'), false);
  assert.ok(escaped.includes('#34;'));
  assert.ok(escaped.includes('#60;'));
  assert.ok(escaped.includes('#62;'));
  assert.ok(escaped.includes('#124;'));
  assert.ok(escaped.includes('#35;'));
  assert.match(escaped, /evil#124;#34;#60;script#62;'#35;/);
});

test('buildModuleDependencyView emits modules and imports edges', () => {
  const policy = loadArchitectureMapPolicy(REPO_ROOT);
  const graph = snapshot(
    [
      node('module:src/core/triwiki', { label: 'triwiki', path: 'src/core/triwiki' }),
      node('module:src/core/errors', { label: 'errors', path: 'src/core/errors' }),
      node('file:src/core/triwiki/a.ts', { kind: 'file', label: 'a.ts', path: 'src/core/triwiki/a.ts' })
    ],
    [
      edge('module:src/core/triwiki', 'module:src/core/errors', 'imports'),
      edge('module:src/core/triwiki', 'file:src/core/triwiki/a.ts', 'contains')
    ]
  );
  const view = buildModuleDependencyView({ snapshot: graph, policy });
  assert.equal(view.viewId, 'module-dependency');
  assert.ok(view.text.startsWith(GENERATED_HEADER));
  assert.match(view.text, /flowchart TD/);
  assert.match(view.text, /imports/);
  assert.ok(view.accounting.emittedNodeIds.includes('module:src/core/triwiki'));
  assert.ok(view.accounting.emittedNodeIds.includes('module:src/core/errors'));
  assert.equal(
    view.accounting.emittedNodeIds.includes('file:src/core/triwiki/a.ts'),
    false,
    'file nodes must be filtered out of module-dependency'
  );
});

test('analyzeArchitectureFindings emits insufficient_graph for empty snapshot', () => {
  const policy = loadArchitectureMapPolicy(REPO_ROOT);
  const empty = snapshot([], []);
  const bundle = buildArchitectureInputBundle({
    rootId: 'test',
    graph: empty,
    policy,
    topologyMode: 'empty'
  });
  const findings = analyzeArchitectureFindings({ bundle, policy });
  assert.ok(findings.length >= 1);
  assert.equal(findings[0]?.code, 'insufficient_graph');
  assert.equal(findings[0]?.severity, 'blocking');
});
