import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import fs from 'node:fs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

async function loadSerializer() {
  const dist = path.join(
    ROOT,
    'dist/core/triwiki/context-graph/projections/mermaid/serializer.js'
  );
  assert.ok(fs.existsSync(dist), 'run npm run build before serializer.test.mjs');
  return import(pathToFileURL(dist).href);
}

async function loadAst() {
  const dist = path.join(ROOT, 'dist/core/triwiki/context-graph/projections/mermaid/ast.js');
  return import(pathToFileURL(dist).href);
}

async function loadIds() {
  const dist = path.join(ROOT, 'dist/core/triwiki/context-graph/projections/mermaid/ids.js');
  return import(pathToFileURL(dist).href);
}

test('serializeMermaidDocument is byte-stable for the minimal fixture graph shape', async () => {
  const { serializeMermaidDocument } = await loadSerializer();
  const ast = await loadAst();
  const { mermaidNodeId } = await loadIds();
  const idA = mermaidNodeId('module:src/a');
  const idB = mermaidNodeId('module:src/b');
  const doc = ast.document({
    direction: 'TD',
    title: 'minimal-ts',
    statements: [
      ast.comment('atlas-view: module-dependency'),
      ast.node({ id: idA, label: 'src/a', canonicalNodeIds: ['module:src/a'] }),
      ast.node({ id: idB, label: 'src/b', canonicalNodeIds: ['module:src/b'] }),
      ast.edge({
        from: idA,
        to: idB,
        relation: 'imports',
        canonicalEdgeIds: ['e1'],
        fromCanonicalId: 'module:src/a',
        toCanonicalId: 'module:src/b'
      })
    ]
  });
  const first = serializeMermaidDocument(doc);
  const second = serializeMermaidDocument(doc);
  assert.equal(first, second);
  assert.match(first, /^%% GENERATED BY SKS\. DO NOT EDIT\./m);
  assert.match(first, /flowchart TD/);
  assert.match(first, /imports/);
});

test('minimal-ts fixture expected view ids are complete', async () => {
  const expectedPath = path.join(
    ROOT,
    'test/fixtures/architecture-map/minimal-ts/expected.json'
  );
  const expected = JSON.parse(fs.readFileSync(expectedPath, 'utf8'));
  assert.equal(expected.fixture, 'minimal-ts');
  assert.equal(expected.expected_view_ids.length, 7);
  assert.deepEqual(expected.expected_finding_codes, []);
});
