/**
 * The v1 `SearchResponse` field map, recorded on the pre-migration engine.
 *
 * Captured by running HEAD's `searchContext` and the migrated one over the same
 * eleven queries against the same fixture graph, in one process, and merging every
 * response into one path -> type map (see `response-shape.ts` for why a merged map
 * rather than a per-response shape).
 *
 * This is a *contract* record, not a result record. It says nothing about which
 * nodes came back or in what order — CRK2 is a different engine and is expected to
 * differ there. It says that no caller-visible field disappeared and none changed
 * type. Regenerate it only when a field is intentionally added or removed, and say
 * so in the same change.
 */
export const V1_SEARCH_RESPONSE_FIELD_MAP: Readonly<Record<string, string>> = Object.freeze({
  "$": "object",
  "$.cacheHit": "boolean",
  "$.confidence": "string",
  "$.context": "object",
  "$.context.excludedCount": "number",
  "$.context.fileHash": "null|string",
  "$.context.graph?": "object",
  "$.context.graph.explanationPathCount": "number",
  "$.context.graph.invalidatedExcluded": "number",
  "$.context.graph.omissionReasons": "object",
  "$.context.graph.omissionReasons.*": "number",
  "$.context.graph.profile": "string",
  "$.context.graph.provenanceCoverage": "number",
  "$.context.graph.seedCount": "number",
  "$.context.graph.selectedNodes": "number",
  "$.context.graph.snapshotFreshness": "string",
  "$.context.graph.snapshotHash": "string",
  "$.context.graph.staleExcluded": "number",
  "$.context.graph.tokenBudget": "number",
  "$.context.graph.tokenCost": "number",
  "$.context.graph.visitedNodes": "number",
  "$.context.hydrated": "boolean",
  "$.context.indexFreshness": "null|string",
  "$.context.method": "string",
  "$.context.repairCommand?": "string",
  "$.context.tokenBudgetOmissions": "number",
  "$.context.truncation": "boolean",
  "$.context.whySearched": "string",
  "$.deterministicOrder": "string",
  "$.durationMs": "number",
  "$.engine": "string",
  "$.errors": "array",
  "$.errors[]?": "string",
  "$.limits": "object",
  "$.limits.maxBytes": "number",
  "$.limits.maxFiles": "number",
  "$.limits.maxMatches": "number",
  "$.limits.timeoutMs": "number",
  "$.matches": "array",
  "$.matches[]": "object",
  "$.matches[].confidence": "string",
  "$.matches[].line?": "number",
  "$.matches[].meta": "object",
  "$.matches[].meta.depth": "number",
  "$.matches[].meta.explanation_steps": "number",
  "$.matches[].meta.freshness": "string",
  "$.matches[].meta.graph_relation": "string",
  "$.matches[].meta.graph_relation_confidence": "string",
  "$.matches[].meta.label": "string",
  "$.matches[].meta.node_id": "string",
  "$.matches[].meta.node_kind": "string",
  "$.matches[].meta.profile": "string",
  "$.matches[].meta.provenance": "array",
  "$.matches[].meta.provenance[]": "object",
  "$.matches[].meta.provenance[].hash": "string",
  "$.matches[].meta.provenance[].line?": "number",
  "$.matches[].meta.provenance[].path": "string",
  "$.matches[].meta.provenance_resolved": "boolean",
  "$.matches[].meta.reason_path": "array",
  "$.matches[].meta.reason_path[]": "string",
  "$.matches[].meta.risk": "string",
  "$.matches[].meta.score": "number",
  "$.matches[].meta.seed": "boolean",
  "$.matches[].meta.seed_confidence?": "string",
  "$.matches[].meta.snapshot_hash": "string",
  "$.matches[].meta.token_cost": "number",
  "$.matches[].meta.trust": "number",
  "$.matches[].path": "string",
  "$.matches[].symbol?": "string",
  "$.mode": "string",
  "$.ok": "boolean",
  "$.processSpawns": "number",
  "$.provider": "string",
  "$.scanned": "object",
  "$.scanned.bytes": "number",
  "$.scanned.files": "number",
  "$.schema": "string",
  "$.schemaVersion": "number",
  "$.skipped": "object",
  "$.skipped.files": "number",
  "$.skipped.reasons": "object",
  "$.skipped.reasons.*": "number",
  "$.timeout": "boolean",
  "$.truncated": "boolean",
  "$.warnings": "array",
  "$.warnings[]?": "string",
});
